---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/ocm-updater"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "onmetal/onmetal-api-maintainers"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "onmetal/onmetal-api-maintainers"
